### ISSUE TITLE
fft2d: wn[n/2] twiddle factor is wrong?

### ISSUE THREAD

**Issue by olajep** [USArmyResearchLab/mpi-epiphany#1]
In generate_wn():

https://github.com/USArmyResearchLab/mpi-epiphany/blob/master/fft2d/main.c#L72

``` c
wn[0] = 1.0f + 0.0f * I;
wn[0 + n2] = conj(wn[0]);
```

shouldn't the second line be this?

``` c
wn[0 + n2] = -1.0f + 0.0f * I;
```

```
wn[0] = e^(-j*2*pi*0/n) = e^0 = 1
wn[n/2] = e^(-j*2*pi*(n/2)/n) = e^(-j*2*pi/2) = e^(-j*pi) = -1
```

Thanks,
Ola

**Comment by jamesaross** [comment]
@olajep,

The results were validated against FFTW.  The complex conjugate is defined as: each of two complex numbers having their real parts identical and their imaginary parts of equal magnitude but opposite sign.

There is no imaginary component for wn[0] so wn[n/2] should be equal to wn[0] in this case.

Regards,
James
