### ISSUE TITLE
coprthr_memcopy_align issue

### ISSUE THREAD

**Issue by jungla88** [USArmyResearchLab/mpi-epiphany#2]
I'm trying to copy data from shared memory into the local memory of a single core.
Following the provided examples such as cannon_uva,mem or addvec, I allocate from the device side some space using :

`buff_size= m*sizeof(float);`
`void* memfree = coprthr_tls_sbrk(0);`
`float* localbuffer = (float*)coprthr_tls_sbrk(buff_size);` 
`coprthr_memcopy_align(localbuffer,c,buff_size,COPRTHR2_M_DMA_0);`

where `c` is `float* c` in host side and it has been allocated in share memory as usual using `memptr` and `dmalloc`(as you do in the examples).

Now suppose that `c` is a matrix but mapped into a vector, if `m` is the number of columns, I should find in `localbuffer` the first row but I have the following result(m=4):
looking into `c` using `host_printf` in device -> `c[0][0->3]= [1000; 1 ; 2 ; 3]`
looking into `localbuffer` I find ->` localbuffer[0->3]=[0.0 ; 1; 2; 3];`

Why the copy miss the first value if I have the correct values in c[0] in the host side?

**Comment by jamesaross** [comment]
Sorry for the late response.  Did you solve this issue?
